# Neden NumPy?

In [24]:
a= [1,2,3,4]
b= [2,3,4,5]


In [26]:
import numpy as np

In [28]:
a= np.array([1,2,3,4])
b= np.array([2,3,4,5])

In [30]:
a*b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [34]:
import numpy as np

In [36]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [38]:
a= np.array([1,2,3,4,5])

In [40]:
type(a)

numpy.ndarray

In [46]:
np.array([3.14, 4, 2, 13])
#burada görüleceği üzere numpy diziyi
# tek bir tipte(sabit) olmaya zorlayıp tüm
# değerleri float olarak verdi

array([ 3.14,  4.  ,  2.  , 13.  ])

In [52]:
np.array([3.14, 4, 2, 13], dtype= "int")
#veya kendimizde olmasını istediğimiz tipi
# seçebiliriz. mesela int yerine float32
# ifadesi de yazılabilir

array([ 3,  4,  2, 13])

In [54]:
#sifirdan array oluşturma

In [56]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.ones((3,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
np.full((3,5),3)
# sadece belirli bir sayıdan array 
# oluşturmak için kullanulır.(örnekteki 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [68]:
np.arange(0,31, 3)
# doğrusal bir dizi oluşturma

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [70]:
np.linspace(0,1,10)
# iki değer arasında, belirli sayıda
# değer oluşturma işlemi

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [72]:
np.random.normal(10, 4, (3,4))
# ortalaması 10, standart sapması 4 olan
# 3e 4lük bir matris verdi
# ve not: tek boyutlu array'in karşılığı
# vektördür. iki boyutlu array'in karşılığı
# matristir.

array([[19.90163976, 10.69858757,  4.09725756,  6.50782455],
       [ 5.17709013, 17.86989731,  2.45027356,  8.69961426],
       [15.09246494, 10.44229624,  7.14874598,  6.5951631 ]])

In [76]:
np.random.randint(0, 10, (3,3))
#0 ve 10 arasında sayı üretir ve 3*3'lük
# matriste belirtir

array([[1, 3, 6],
       [6, 0, 0],
       [4, 0, 4]])

In [78]:
# np.arange()
# np.random.normal()
# np.random.randint()
# bunlar sıklıkla kullanılacak olanlar

# Özellikleri
* **ndim:** _boyut sayısı_
* **shape:** boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [114]:
# video 117
# bir üst satırdaki markdown'un nasıl
# yazıldığına daha sonra tekrar bak

In [117]:
import numpy as np

In [119]:
np.random.randint(10, size= 10)

array([7, 8, 9, 9, 5, 0, 6, 4, 6, 6])

In [121]:
a = np.random.randint(10, size= 10)

In [123]:
a.ndim

1

In [125]:
a.shape

(10,)

In [127]:
a.size

10

In [129]:
a.dtype

dtype('int32')

In [132]:
b= np.random.randint(10, size= (3,5))

In [134]:
b

array([[6, 3, 2, 7, 6],
       [5, 9, 2, 5, 0],
       [9, 1, 5, 0, 2]])

In [136]:
b.ndim

2

In [138]:
b.shape

(3, 5)

In [140]:
b.size

15

In [142]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme(reshaping)

In [147]:
# Video118 yeniden şekillendirme(reshaping)

In [149]:
import numpy as np

In [157]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
a= np.arange(1,10)

In [163]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
a.ndim

1

In [179]:
b= a.reshape((1,9))

In [181]:
b.ndim

2

# Array Birleştirme(Concatenation)

In [184]:
# Video 119

In [186]:
import numpy as np

In [188]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [192]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [194]:
z= np.array([7,8,9])

In [196]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
# iki boyutlu 

In [200]:
a= np.array([[1,2,3], 
             [4,5,6]])

In [208]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [219]:
# bir üst hücrede satır bazında birleştirme
# yapıldı. sütun bazında yapmak için
# axis değeri default olarak 0'dır yani 
# satır bazında birleştirir.
# eğer axis değerini 1 yaparsak sütun
# bazında birleştirme yapar
# yani 0 satırları, 1 sütunları ifade eder

In [225]:
np.concatenate([a,a], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [228]:
import numpy as np

In [230]:
x= np.array([1,2,3,99,99,3,2,1])

In [232]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [234]:
a,b,c = np.split(x, [3,5])

In [236]:
a

array([1, 2, 3])

In [238]:
b

array([99, 99])

In [240]:
c

array([3, 2, 1])

In [242]:
# iki boyutlu

In [258]:
m= np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [270]:
np.vsplit(m, [2])
# vsplit ile dikey olarak ekledi

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [272]:
ust, alt= np.vsplit(m, [2])

In [274]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [276]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [279]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [281]:
np.hsplit(m,[2])
# hsplit ile yatay olarak ekledi

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [283]:
sag, sol = np.hsplit(m,[2])


In [285]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [287]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama(Sorting)

In [290]:
import numpy as np

In [292]:
v= np.array([2,1,4,3,5])

In [294]:
v

array([2, 1, 4, 3, 5])

In [296]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [298]:
v

array([2, 1, 4, 3, 5])

In [304]:
v.sort()
# numpy olmadan yapıldığında verinin 
# orijinal yapısını bozmuş olduk

In [306]:
v

array([1, 2, 3, 4, 5])

In [308]:
# iki boyutlu

In [316]:
o= np.random.normal(20,5, (3,3))

In [318]:
o

array([[22.40570198, 25.60384615, 19.65450269],
       [21.1616907 , 27.60270833, 20.67438397],
       [18.97934159, 17.69783451, 26.79168604]])

In [320]:
np.sort(m, axis= 1)

array([[16.93295082, 25.21389595, 28.29831542],
       [16.37143347, 16.37467852, 24.35457252],
       [10.06779816, 16.06574766, 23.93294488]])

In [322]:
np.sort(m, axis= 0)

array([[16.06574766, 16.37467852, 10.06779816],
       [24.35457252, 16.93295082, 16.37143347],
       [28.29831542, 23.93294488, 25.21389595]])

# Index ile elemanlara erişmek (Video 122)

In [3]:
import numpy as np
a= np.random.randint(10, size=10)
a

array([4, 8, 5, 1, 6, 0, 0, 9, 6, 1])

In [5]:
a[0]

4

In [7]:
a[-1]

1

In [9]:
a[0]= 15

In [11]:
a

array([15,  8,  5,  1,  6,  0,  0,  9,  6,  1])

In [13]:
m= np.random.randint(10, size=(3,5)) #iki boyutlu array
m

array([[1, 7, 8, 6, 1],
       [3, 1, 2, 2, 7],
       [8, 1, 9, 5, 9]])

In [15]:
m[0,0]

1

In [17]:
m[1,4]

7

In [19]:
m[1,4]=99

In [21]:
m

array([[ 1,  7,  8,  6,  1],
       [ 3,  1,  2,  2, 99],
       [ 8,  1,  9,  5,  9]])

In [23]:
m[1,4]= 2.2

In [27]:
m
# 2.2nin ondalık kısmını eklemedi, sadece 2 olarak ekledi
# arrayin tipi int
# dışarıdan farklı tipte atama gerçekleşsede
# int olarak ekledi, ondalık kısmını almadı

array([[1, 7, 8, 6, 1],
       [3, 1, 2, 2, 2],
       [8, 1, 9, 5, 9]])

# Array Alt Küme İşlemleri(Slicing) (Video 123)

In [31]:
# Slicing ile Elemanlara erişmek
# (Array alt kümesine erişmek)

In [33]:
import numpy as np

In [35]:
a= np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
# a[0:3] ifadesindeki ":" slice işlemine denk gelir

In [41]:
a[0:3]

array([20, 21, 22])

In [43]:
a[:3]

array([20, 21, 22])

In [45]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [47]:
a[1::2]

array([21, 23, 25, 27, 29])

In [49]:
a[0::2]

array([20, 22, 24, 26, 28])

In [51]:
a[0::3]

array([20, 23, 26, 29])

In [53]:
# iki boyutlu slice işlemleri

In [55]:
m= np.random.randint(10, size=(5,5))

In [57]:
m

array([[4, 7, 2, 4, 9],
       [5, 5, 5, 5, 1],
       [2, 3, 1, 4, 2],
       [8, 0, 3, 8, 4],
       [1, 6, 6, 7, 2]])

In [59]:
m[:,0]

array([4, 5, 2, 8, 1])

In [61]:
m[:,4]

array([9, 1, 2, 4, 2])

In [63]:
m[0,:]

array([4, 7, 2, 4, 9])

In [65]:
m[0]

array([4, 7, 2, 4, 9])

In [67]:
m[1,:]

array([5, 5, 5, 5, 1])

In [69]:
m[0:2, 0:3]

array([[4, 7, 2],
       [5, 5, 5]])

In [73]:
m[::,:2]
#veya m[::, 0:2]

array([[4, 7],
       [5, 5],
       [2, 3],
       [8, 0],
       [1, 6]])

In [75]:
m[1:3, 0:2]

array([[5, 5],
       [2, 3]])

# Alt Küme Üzerinde İşlem Yapmak (Video 124)

In [78]:
import numpy as np
a= np.random.randint(10, size=(5,5))
a

array([[6, 3, 5, 3, 2],
       [5, 8, 0, 1, 1],
       [3, 1, 6, 8, 0],
       [1, 5, 0, 3, 3],
       [0, 4, 2, 1, 6]])

In [80]:
alt_a= a[0:3, 0:2]
alt_a

array([[6, 3],
       [5, 8],
       [3, 1]])

In [82]:
alt_a[0,0]=99999
alt_a[1,1]=888

In [84]:
alt_a

array([[99999,     3],
       [    5,   888],
       [    3,     1]])

In [89]:
a

array([[99999,     3,     5,     3,     2],
       [    5,   888,     0,     1,     1],
       [    3,     1,     6,     8,     0],
       [    1,     5,     0,     3,     3],
       [    0,     4,     2,     1,     6]])

In [93]:
m= np.random.randint(10, size=(5,5))
m

array([[5, 1, 0, 6, 3],
       [1, 7, 7, 3, 0],
       [9, 6, 6, 8, 2],
       [3, 8, 5, 6, 7],
       [3, 4, 2, 2, 6]])

In [97]:
alt_b= m[0:3, 0:2].copy()
alt_b
# copy methodu ile ana arrayden bağımsız 
# olarak işlem yapılır

array([[5, 1],
       [1, 7],
       [9, 6]])

In [99]:
alt_b[0,0]=9999

In [101]:
alt_b

array([[9999,    1],
       [   1,    7],
       [   9,    6]])

In [103]:
m

array([[5, 1, 0, 6, 3],
       [1, 7, 7, 3, 0],
       [9, 6, 6, 8, 2],
       [3, 8, 5, 6, 7],
       [3, 4, 2, 2, 6]])

In [107]:
# oluşturmuş olduğumuz ilk arrayin yapısında
# hiçbir bozukluk meydana gelmedi.
# fakat seçmiş olduğumuz alt küme üzerinde
# bir değişiklik yapmış olduk..

# Fancy Index ile Elemanlara Erişmek(Video 125)

In [112]:
#burası önemli

In [114]:
import numpy as np
v= np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [116]:
v[1]

3

In [118]:
v[3]

9

In [120]:
v[5]

15

In [122]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [124]:
al_getir= [1,3,5]

In [126]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [128]:
v[al_getir]

array([ 3,  9, 15])

In [130]:
# iki boyutta fancy

In [132]:
m= np.arange(9).reshape((3,3))

In [134]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
satir= np.array([0,1])
sütun= np.array([1,2])

In [138]:
m[satir, sütun]

array([1, 5])

In [140]:
# basit index ile fancy index

In [142]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [144]:
m[0, [1,2]]

array([1, 2])

In [150]:
#slice ile fancy

In [154]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri(Video 126)

In [157]:
import numpy as np
v = np.array([1,2,3,4,5])

In [161]:
v <3

array([ True,  True, False, False, False])

In [165]:
v[v<3]
#aslında burada da fancy işleminden 
#yararlanıldı

array([1, 2])

In [167]:
v[v>3]

array([4, 5])

In [169]:
v[v>=3]

array([3, 4, 5])

In [171]:
v[v<=3]

array([1, 2, 3])

In [173]:
v[v==3]

array([3])

In [175]:
v[v!=3]

array([1, 2, 4, 5])

In [177]:
v

array([1, 2, 3, 4, 5])

In [179]:
v*2

array([ 2,  4,  6,  8, 10])

In [181]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [183]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [185]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler(Video 127)

In [188]:
import numpy as np
v= np.array([1,2,3,4,5])

In [190]:
v-1

array([0, 1, 2, 3, 4])

In [192]:
v*5

array([ 5, 10, 15, 20, 25])

In [194]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [196]:
# ufunc

In [198]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [200]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [202]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [204]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [206]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [210]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [212]:
np.absolute(np.array([-3]))

array([3])

In [214]:
np.sin(360)

0.9589157234143065

In [216]:
np.cos(180)

-0.5984600690578581

In [218]:
v= np.array([1,2,3])

In [220]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [222]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [224]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [226]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\mert\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\mert\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

In [230]:
#cheat sheet

In [232]:
#örneğin google'da "numpy mathematics cheatsheet"
# diye aratırsak her şeyi görebilirsin

In [234]:
# bi üst satırdaki not gerçekten çok önemli
# ve çok kullanışlı

# İstatistiksel Hesaplamalar

In [237]:
"""MEAN

np.mean(arr, axis=0)
Returns mean of arr along specified axis

SUM

arr.sum()
Returns the sum of elements in arr

MIN

arr.min()
Returns minimum value of arr

MAX

arr.max(axis=0)
Returns maximum value of arr along specified axis

VAR

np.var(arr)
Returns the variance of arr

STD

np.std(arr, axis=1)
Returns the standard deviation of arr along specified axis

CORRCOEF

arr.corrcoef()
Returns correlation coefficient of arr
"""
# bu notların tamamı cheat sheet olarak
# google'da aratılarak alındı

'MEAN\n\nnp.mean(arr, axis=0)\nReturns mean of arr along specified axis\n\nSUM\n\narr.sum()\nReturns the sum of elements in arr\n\nMIN\n\narr.min()\nReturns minimum value of arr\n\nMAX\n\narr.max(axis=0)\nReturns maximum value of arr along specified axis\n\nVAR\n\nnp.var(arr)\nReturns the variance of arr\n\nSTD\n\nnp.std(arr, axis=1)\nReturns the standard deviation of arr along specified axis\n\nCORRCOEF\n\narr.corrcoef()\nReturns correlation coefficient of arr\n'

In [239]:
# bu cheat sheet olayını mutlaka bir eğitim
# aldığında yapmalısın çünkü eğitmenler
# bir konuyla ilgili tüm konulara
# değinmeyebiliyorlar

# Numpy ile İki Bilinmeyenli Denklem Çözümü(Video 128)

In [244]:
import numpy as np

5*x0+x1=12

x0+3*x1=10

In [254]:
a= np.array([[5,1], [1,3]])
b= np.array([12,10])

In [256]:
a

array([[5, 1],
       [1, 3]])

In [258]:
b

array([12, 10])

In [260]:
x= np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

# Pandas Giris (Video 129)

In [3]:
"""PANDAS

-Panel Data
-Veri manipülasyonu ve veri analizi için yazılmış açık kaynak kodlu bir python kütüphanesidir
-Ekonometrik ve finansal çalışmalar için doğmuştur
-Temeli 2008 yılında atılmıştır
- R DataFrame yapısını Python dünyasına taşımış ve DataFrame'ler üzerinde hızlı ve etkili çalışabilme imkanı sağlamıştır
"""

"PANDAS\n\n-Panel Data\n-Veri manipülasyonu ve veri analizi için yazılmış açık kaynak kodlu bir python kütüphanesidir\n-Ekonometrik ve finansal çalışmalar için doğmuştur\n-Temeli 2008 yılında atılmıştır\n- R DataFrame yapısını Python dünyasına taşımış ve DataFrame'ler üzerinde hızlı ve etkili çalışabilme imkanı sağlamıştır\n"

# Pandas Serisi Oluşturmak (Video 130)

In [6]:
import pandas as pd

In [8]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
# yukarda ilk sütundakiler indexleri ifade eder
# diğerleri ise içindeki değerlerdir

In [12]:
# pandas içinde yer alan veri tipleri
# değerleri indexleri ile beraber tutar

In [14]:
seri= pd.Series([1,2,3,4,5])

In [16]:
type(seri)

pandas.core.series.Series

In [20]:
seri.axes
#serinin index bilgilerine erişmeyi sağlar

[RangeIndex(start=0, stop=5, step=1)]

In [22]:
seri.dtype
#serinin içindeki değerler hakkında bilgi verir

dtype('int64')

In [24]:
seri.size

5

In [26]:
seri.ndim
#boyut bilgisini verir

1

In [28]:
seri.values

array([1, 2, 3, 4, 5], dtype=int64)

In [34]:
seri.head(3)
#serinin ilk 3 gözlemini getirir

0    1
1    2
2    3
dtype: int64

In [42]:
seri.tail(3)
#serinin son 3 gözlemini getirir

2    3
3    4
4    5
dtype: int64

In [45]:
#index isimlendirmesi

In [47]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [55]:
pd.Series([99,22,332,94,5],index=[1,3,5,7,9])
#indexleri bizim verdiğimiz şekilde değiştirir

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [57]:
#indexleri ayrıca int yerine string veri tipinde de
#değiştirebiliriz

In [59]:
pd.Series([99,22,332,94,5],index=["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [61]:
seri= pd.Series([99,22,332,94,5],index=["a","b","c","d","e"])

In [63]:
seri["a"]

99

In [65]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [67]:
#Yukarıda pandas serisini hep liste üzerinden oluşturduk
#Bunu farklı veri yapıları üzerinden de oluşturabiliriz
#Örneğin sözlük üzerinden liste oluşturma

In [69]:
#Sözlük üzerinden liste oluşturma

In [83]:
sozluk= {"reg":10, "log":11, "cart": 12}

In [85]:
seri= pd.Series(sozluk)

In [87]:
seri

reg     10
log     11
cart    12
dtype: int64

In [89]:
#iki seriyi birleştirerek seri oluşturma

In [91]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri (Video 131)

In [94]:
import numpy as np
a= np.array([1,2,33,444,75])
seri= pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [96]:
seri[0]

1

In [98]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [100]:
seri= pd.Series([121,200,150,99], index=["reg", "loj", "cart", "rf"])

In [102]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [104]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [106]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [108]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [110]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [113]:
#eleman sorgulama

In [117]:
"reg" in seri
# reg ifadesi seri değişkeninin içinde mi

True

In [119]:
"a" in seri

False

In [121]:
seri["reg"]

121

In [123]:
#fancy eleman

In [127]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [133]:
seri["reg"]= 130
#121 idi, 130 olarak değiştirdik

In [135]:
seri["reg"]

130

In [139]:
seri["reg": "loj"]
# reg'den loj'a kadar çıktı verir

reg    130
loj    200
dtype: int64

# Pandas DataFrame Oluşturma (Video 132)

In [142]:
import pandas as pd

In [144]:
l= [1,2,39,67,90]

In [146]:
l

[1, 2, 39, 67, 90]

In [152]:
pd.DataFrame(l, columns= ["degisken_ismi"])
#burası önemli, columns değişkeni yerine
#kafana göre değişken veremezsin diye anladım

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [160]:
import numpy as np
m= np.arange(1,10).reshape((3,3))
m
#arange fonksiyonu, belirli bir aralıkta 
#düzenli artan değerler içeren bir dizi 
#(array) oluşturmak için kullanılır

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
pd.DataFrame(m, columns= ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [172]:
#yukarıda 2 boyutlu bir DataFrame oluşturmuş olduk

In [174]:
# DataFrame'ler veri bilimi ve yapay zeka
# kapsamında en sık kullanacak olduğumuz
# veri yapılarıdır

In [176]:
#df isimlendirme (dataframe)

In [180]:
df= pd.DataFrame(m, columns= ["var1", "var2", "var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [184]:
df.columns= ("deg1", "deg2", "deg3")
#degisken isimleri var1, var2, var3tü
#onları değiştirdik


In [186]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [188]:
type(df)

pandas.core.frame.DataFrame

In [190]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [196]:
df.shape
#boyut bilgisi veir

(3, 3)

In [198]:
df.ndim
#boyut sayısını verir

2

In [205]:
df.values
#dataframe tipindeki veri yapısının içerisinden
#sadece değerleri çekip, bunları numpy arrayine
#yani ndarray nesnesine dönüştürdü
#(aşağıda tip sorgusunda da görünüyor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [207]:
type(df.values)

numpy.ndarray

In [209]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [213]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [219]:
#numpy arrayi üzerinden dataframe oluşturma

In [215]:
a= np.array([1,2,3,4,5])

In [217]:
pd.DataFrame(a, columns= ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Pandas DataFrame Eleman İşlemleri (Video 133)

In [1]:
#sıfırdan dataframe oluşturalım

In [12]:
import pandas as pd

In [14]:
import numpy as np
s1= np.random.randint(10, size= 5)
s2= np.random.randint(10, size= 5)
s3= np.random.randint(10, size= 5)


In [16]:
sozluk= {"var1": s1, "var2": s2, "var3": s3}

In [18]:
sozluk

{'var1': array([5, 7, 1, 8, 8]),
 'var2': array([7, 5, 2, 3, 7]),
 'var3': array([6, 9, 0, 6, 5])}

In [20]:
df= pd.DataFrame(sozluk)

In [22]:
df

var1  var2  var3
0     5     7     6
1     7     5     9
2     1     2     0
3     8     3     6
4     8     7     5

In [24]:
df[0:1]

var1  var2  var3
0     5     7     6

In [26]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
df.index= ["a", "b", "c", "d", "e"]
#index değiştirme

In [34]:
df

var1  var2  var3
a     5     7     6
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [36]:
df["c":"e"]

var1  var2  var3
c     1     2     0
d     8     3     6
e     8     7     5

In [38]:
# silme islemi

In [40]:
df.drop("a", axis= 0)

var1  var2  var3
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [44]:
df
# gözlemlendiği gibi silme işleminden
# sonra veri setinin 
# ana yapısında bir değişiklik olmadı

var1  var2  var3
a     5     7     6
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [46]:
df.drop("a", axis=0, inplace= True)
# inplace DataFrame üzerinde yapılan
# değişikliğin kalıcı olmasını sağlar

In [48]:
df

var1  var2  var3
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [50]:
# fancy

In [52]:
l= ["c", "e"]

In [54]:
df.drop(l, axis= 0)

var1  var2  var3
b     7     5     9
d     8     3     6

In [56]:
# değişkenler için

In [58]:
df

var1  var2  var3
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [60]:
"var1" in df

True

In [62]:
l= ["var1", "var4", "var2"]

In [64]:
for i in l:
    print(i in df)

True
False
True


In [66]:
df

var1  var2  var3
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [70]:
df["var1"]

b    7
c    1
d    8
e    8
Name: var1, dtype: int32

In [72]:
df["var4"]= df["var1"] / df["var2"]

In [74]:
df

var1  var2  var3      var4
b     7     5     9  1.400000
c     1     2     0  0.500000
d     8     3     6  2.666667
e     8     7     5  1.142857

In [76]:
# degisken silmek

In [78]:
df.drop("var4", axis= 1)

var1  var2  var3
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [80]:
df

var1  var2  var3      var4
b     7     5     9  1.400000
c     1     2     0  0.500000
d     8     3     6  2.666667
e     8     7     5  1.142857

In [82]:
df.drop("var4", axis= 1, inplace= True)

In [84]:
df

var1  var2  var3
b     7     5     9
c     1     2     0
d     8     3     6
e     8     7     5

In [86]:
l= ["var1", "var2"]

In [88]:
df.drop(l, axis= 1)

var3
b     9
c     0
d     6
e     5

# Gözlem ve Değişken Seçimi: loc & iloc (Video 134)

In [99]:
?np.random.randint
#kullanımı unuttuysak böyle yapmalıyız

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [101]:
import numpy as np
import pandas as pd
m= np.random.randint(1,30, size=(10,3))
df= pd.DataFrame(m, columns= ["var1", "var2", "var3"])
df

var1  var2  var3
0    16    24     1
1    21    12    16
2    24    16     3
3     6     5    18
4    22    26    11
5     8    27    15
6    22    21     8
7    14    12    16
8    16    23    14
9    28    10    20

In [103]:
#loc: tanımlandığı şekli ile seçim yapmak
# için kullanılır

In [105]:
df.loc[0:3]

var1  var2  var3
0    16    24     1
1    21    12    16
2    24    16     3
3     6     5    18

In [107]:
#iloc: alışık olduğumuz indexleme mantığı
# ile seçim yapar

In [109]:
df.iloc[0:3]

var1  var2  var3
0    16    24     1
1    21    12    16
2    24    16     3

In [111]:
df.iloc[0,0]

16

In [113]:
df.iloc[:3,:2]

var1  var2
0    16    24
1    21    12
2    24    16

In [115]:
df.loc[0:3, "var3"]

0     1
1    16
2     3
3    18
Name: var3, dtype: int32

In [119]:
df.loc[0:3, "var3"]

0     1
1    16
2     3
3    18
Name: var3, dtype: int32

In [121]:
df.iloc[0:3, 1:3]

var2  var3
0    24     1
1    12    16
2    16     3

In [123]:
df.iloc[0:3] ["var3"]

0     1
1    16
2     3
Name: var3, dtype: int32

# Koşullu Eleman İşlemleri (Video 135)

In [1]:
import numpy as np
import pandas as pd
m= np.random.randint(1,30, size= (10,3))
df= pd.DataFrame(m, columns= ["var1", "var2", "var3"])
df

var1  var2  var3
0    20    25    16
1    13    21     3
2    19    11    25
3    28    21    12
4     2    17     8
5    29    25    24
6    28    26     1
7     4    11    26
8    14    17    11
9    11    27     1

In [12]:
df["var1"]

0    20
1    13
2    19
3    28
4     2
5    29
6    28
7     4
8    14
9    11
Name: var1, dtype: int32

In [16]:
df["var1"][0:2]

0    20
1    13
Name: var1, dtype: int32

In [18]:
df[0:2]

var1  var2  var3
0    20    25    16
1    13    21     3

In [28]:
df[0:2][["var1", "var2"]]
#çift parantez kulanımı (fancy)
#birden fazla sütun için fancy kullanılmalı

var1  var2
0    20    25
1    13    21

In [30]:
df

var1  var2  var3
0    20    25    16
1    13    21     3
2    19    11    25
3    28    21    12
4     2    17     8
5    29    25    24
6    28    26     1
7     4    11    26
8    14    17    11
9    11    27     1

In [32]:
df.var1

0    20
1    13
2    19
3    28
4     2
5    29
6    28
7     4
8    14
9    11
Name: var1, dtype: int32

In [42]:
df[df.var1> 15]["var2"]

0    25
2    11
3    21
5    25
6    26
Name: var2, dtype: int32

In [44]:
df[(df.var1> 15) & (df.var3< 5)]

var1  var2  var3
6    28    26     1

In [50]:
df.loc[(df.var1> 15), ["var1", "var2"]]
#bunun başında loc olmazsa hata alırız
#type error hatası

var1  var2
0    20    25
2    19    11
3    28    21
5    29    25
6    28    26

In [52]:
df[(df.var1> 15)][["var1", "var2"]]

var1  var2
0    20    25
2    19    11
3    28    21
5    29    25
6    28    26

# Birleştirme(Join) İşlemleri (Video 136)

In [59]:
import numpy as np
import pandas as pd
m= np.random.randint(1,30, size=(5,3))
df1= pd.DataFrame(m, columns= ["var1", "var2", "var3"])
df1

var1  var2  var3
0     8    18    13
1     7    16    15
2    16    15     6
3    10    27    23
4    10    16     2

In [61]:
df2= df1+99

In [63]:
df2

var1  var2  var3
0   107   117   112
1   106   115   114
2   115   114   105
3   109   126   122
4   109   115   101

In [75]:
pd.concat([df1,df2])
#iki dataframe'i birleştirme işlemi
#lakin biraz sıkıntılı
# sıkıntı şu: index numaraları

var1  var2  var3
0     8    18    13
1     7    16    15
2    16    15     6
3    10    27    23
4    10    16     2
0   107   117   112
1   106   115   114
2   115   114   105
3   109   126   122
4   109   115   101

In [73]:
?pd.concat
#yukarıdaki problemi çözmek adına
#bunu yapıyoruz

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [77]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0     8    18    13
1     7    16    15
2    16    15     6
3    10    27    23
4    10    16     2
5   107   117   112
6   106   115   114
7   115   114   105
8   109   126   122
9   109   115   101

In [81]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [83]:
df2.columns=["var1", "var2", "deg3"]

In [85]:
df2

var1  var2  deg3
0   107   117   112
1   106   115   114
2   115   114   105
3   109   126   122
4   109   115   101

In [87]:
df1

var1  var2  var3
0     8    18    13
1     7    16    15
2    16    15     6
3    10    27    23
4    10    16     2

In [91]:
pd.concat([df1,df2])
#çıktısında problem var
#deg3 her ikisinde de olmadığı için
#NaN hatası aldık

var1  var2  var3   deg3
0     8    18  13.0    NaN
1     7    16  15.0    NaN
2    16    15   6.0    NaN
3    10    27  23.0    NaN
4    10    16   2.0    NaN
0   107   117   NaN  112.0
1   106   115   NaN  114.0
2   115   114   NaN  105.0
3   109   126   NaN  122.0
4   109   115   NaN  101.0

In [95]:
pd.concat([df1,df2], join="inner")
#birleştirme işlemini kesişimlerine göre
# yaptı

var1  var2
0     8    18
1     7    16
2    16    15
3    10    27
4    10    16
0   107   117
1   106   115
2   115   114
3   109   126
4   109   115

In [99]:
pd.concat([df1,df2], join_axes= [df1.columns])
#join_axes argümanı concat içinde tanımlı
#değil hatası alıyorum çözemedim

TypeError: concat() got an unexpected keyword argument 'join_axes'

# İleri Birleştirme İşlemleri(Video 137)

In [102]:
import pandas as pd

In [104]:
#birebir birleştirme

In [106]:
df1= pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                  'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'IK']})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [108]:
df2= pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                  'ilk_giris': [2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [110]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [112]:
pd.merge(df1, df2, on= "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [114]:
#çoktan teke

In [116]:
df3= pd.merge(df1, df2)

In [118]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [120]:
df4= pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'IK'],
                  'mudur': ['Caner', 'Mustafa', 'Berkcan']})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [122]:
pd.merge(df3, df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           IK       2019  Berkcan

In [125]:
#çoktan çoka

In [127]:
df5= pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe', 'Muhendislik', 'Muhendislik', 'IK', 'IK'],
                  'yetenekler': ['matematik', 'excel', 'kodlama', 'linux', 'excel', 'yonetim']})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [129]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [131]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           IK      excel
7      Fatma           IK    yonetim

# Toplulaştırma ve Gruplama(Aggregation & Grouping) (Video 138)

Basit toplulaştırma fonksiyonları:

-count()

-first()

-last()

-mean()

-median()

-min()

-max()

-std()

-var()

-sum()

In [138]:
import seaborn as sns

In [140]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [142]:
df= sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [144]:
df.shape

(1035, 6)

In [150]:
?df.mean()
#burayı çözemedim

Object `df.mean()` not found.


In [152]:
df["mass"].mean()

2.6381605847953216

In [154]:
df["mass"].count()

513

In [156]:
df["mass"].min()

0.0036

In [158]:
df["mass"].max()

25.0

In [160]:
df["mass"].sum()

1353.37638

In [164]:
df["mass"].std()
#standart sapma

3.8186166509616046

In [166]:
df["mass"].var()
#varyans

14.58183312700122

In [170]:
df.describe()
#pandas kütüphanesinde bir DataFrame'in 
#temel istatistiksel özetini verir. 
#Bu işlev, sayısal sütunlar için aşağıdaki 
#istatistikleri otomatik olarak hesaplar:

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [174]:
df.describe().T
#transpozesini yani tersini aldı

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [176]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri (Video 139)

In [179]:
df= pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                 'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [181]:
 df.groupby("gruplar")

In [183]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [185]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [187]:
df= sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [189]:
df.groupby("method")

In [191]:
df.groupby("method")["orbital_period"]

In [193]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [195]:
df.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [199]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# Aggregate (Video 140)

İleri Toplulaştırma İşlemleri

(Aggregate, filter, transform, apply)

In [12]:
#bu bölüm önemli

In [24]:
import numpy as np
import pandas as pd
df= pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken2': [100,253,333,262,111,969]},
                columns= ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [26]:
#aggregate

In [28]:
df.groupby("gruplar")

In [30]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [36]:
df.groupby("gruplar").aggregate(["min", np.median, max])

# df DataFrame'inde "gruplar" sütunundaki değerlere göre gruplama yapar. Yani, "gruplar" sütunundaki her benzersiz değer için ayrı bir grup oluşturulur.
# Parantezin içinde ise Gruplandırılmış veriler üzerinde belirtilen istatistiksel işlemleri uygular.

# "min": Her grup için her sütunun minimum değerini hesaplar.

# np.median: Her grup için her sütunun medyan (ortanca) değerini hesaplar.

# "max": Her grup için her sütunun maksimum değerini hesaplar.

# ve parantezin içindeki min ve max ifadesi
# tırnaklar içinde olsa veya olmasa da pandas bunları algılar
# ama np.median ifadesi tırnaklar içine alınsaydı hata alırdık

C:\Users\mert\AppData\Local\Temp\ipykernel_7788\3732139054.py:1: FutureWarning: The provided callable <function median at 0x0000017C34839440> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby("gruplar").aggregate(["min", np.median, max])
C:\Users\mert\AppData\Local\Temp\ipykernel_7788\3732139054.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("gruplar").aggregate(["min", np.median, max])


degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [38]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

# filter (Video 141)

In [41]:
#filter

In [43]:
import pandas as pd
df= pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken2': [100,253,333,262,111,969]},
                columns= ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [45]:
def filter_func(x):
    return x["degisken1"].std()>9

In [49]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [47]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

# transform (Video 142)

In [52]:
#transform

In [54]:
import pandas as pd
df= pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken2': [100,253,333,262,111,969]},
                columns= ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [56]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [64]:
df_a= df.iloc[:,1:3]

In [66]:
df_a.transform(lambda x: x-x.mean())

degisken1  degisken2
0      -23.0     -238.0
1      -10.0      -85.0
2        0.0       -5.0
3      -11.0      -76.0
4      -22.0     -227.0
5       66.0      631.0

In [70]:
df_a.transform(lambda x: (x-x.mean()) / x.std())
#transform fonksiyonu vektörel çalışan bi fonk.
# yani sütun bazında, değişkenler bazında, bütün değişkenlerin üzerinde bi işlem yapmak için kullandığımız bi fonk.

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

# apply (Video 143)

In [85]:
import pandas as pd
df= pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken2': [100,253,333,262,111,969]},
                columns= ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [81]:
df.apply(np.sum)
#degiskenleri topladık

degisken1     198
degisken2    2028
dtype: int64

In [83]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [87]:
df.groupby("gruplar").apply(np.sum)

C:\Users\mert\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\mert\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\mert\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwa

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         34        364
C            CC        132       1302

In [89]:
df.groupby("gruplar").apply(np.mean)

gruplar
A     98.5
B     99.5
C    358.5
dtype: float64

# Pivot Tablolar (Video 144)

In [92]:
import pandas as pd
import seaborn as sns
titanic= sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [94]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [97]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [103]:
titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean").unstack()
# unstack() hiyerarşik index yapısı sağlar
# unstack() olmasa da olur

C:\Users\mert\AppData\Local\Temp\ipykernel_7788\4117870810.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean").unstack()


survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [105]:
# pivot ile table

In [107]:
titanic.pivot_table("survived", index= "sex", columns= "class")

C:\Users\mert\AppData\Local\Temp\ipykernel_7788\1855427861.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", index= "sex", columns= "class")


class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [109]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [111]:
age= pd.cut(titanic["age"], [0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [115]:
titanic.pivot_table("survived", ["sex", age], "class")
#tırnakla belirtip belirtmeme durumları önemli

C:\Users\mert\AppData\Local\Temp\ipykernel_7788\1375024267.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", ["sex", age], "class")


class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okuma (Video 145)

In [8]:
#reading_data isimli dış kaynak verisi
#üzerinde işlemler yapılacak

In [2]:
import pandas as pd

In [14]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '

In [10]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep= ";")
# csv formundaki dış kaynaklı verileri
#okurken sep=; ifadesini kullanmazsak
#okuma hatası alabiliriz

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [16]:
#txt okuma
#csv formatı txt formatını okuyabiliyor
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [20]:
#excel
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [22]:
df= pd.read_excel("reading_data/ornekx.xlsx")

In [24]:
type(df)

pandas.core.frame.DataFrame

In [26]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [28]:
df.columns= ("A", "B", "C")

In [30]:
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [34]:
#bu video çeşitli platformlardan farklı tiplerdeki verileri
#istediğimiz tipe dönüştürüp okuma ile alakalı idi.
#bazı kısımları not alamadım tekrar amaçlı videoyu izleyebilirsin

# Problem Çözme ve Doküman Okuma Kültürü (Video 146)

In [37]:
"""videoda, karşılaştığımız hataları; problemleri
problemin hatanın son satırındaki yazıyı alıp googleda aratarak
veya stacoverflow'da aratarak ilgili hata ile ilgili diğer insanların
çözümlerini görebileceğimize değinildi"""
# örnek olarak 9/0 yazdığımızda aldığımız hatayı deneyebiliriz

"videoda, karşılaştığımız hataları; problemleri\nproblemin hatanın son satırındaki yazıyı alıp googleda aratarak\nveya stacoverflow'da aratarak ilgili hata ile ilgili diğer insanların\nçözümlerini görebileceğimize değinildi"

In [39]:
"""doküman okuma ile ilgilide örnek olarak pandas'in tüm dokümanlarına 
nasıl erişebileceğimize değinildi. google'a pandas documentation diye yazdığımzda pandas ile ilgili tüm bilgileri görebiliriz.
ayrıca pandas dışında başka bilgilere erişmek istersek
benzer bir yol izleyerek ilgili bilgiye ulaşabiliriz"""

"doküman okuma ile ilgilide örnek olarak pandas'in tüm dokümanlarına \nnasıl erişebileceğimize değinildi. google'a pandas documentation diye yazdığımzda pandas ile ilgili tüm bilgileri görebiliriz.\nayrıca pandas dışında başka bilgilere erişmek istersek\nbenzer bir yol izleyerek ilgili bilgiye ulaşabiliriz"

In [41]:
"""ayrıca cheetsheet'te bunlara dahil"""

"ayrıca cheetsheet'te bunlara dahil"